### ISSUE TITLE
ideia: class Order e internacionalização

### ISSUE THREAD

**Issue by alexandrebini** [algorich/pagseguro#2]
Estou com algumas ideias aqui e gostaria de saber sua opinião. Se você achar que vale a pena, eu implemento e faço um pull.

Primeiramente, criar um locale (pagseguro.yml) traduzindo as mensagens de erro: https://pagseguro.uol.com.br/v2/guia-de-integracao/codigos-de-erro.html

Fazer a classe Order extender o ActiveModel, assim poderíamos fazer algumas validações diretamente na classe (requerer itens, valor, etc...). 

Ainda na classe Order, adicionaríamos o método post (que está atualmente em action_controller). Quando chamamos tal método, e em caso de sucesso deixaríamos ali o  código e a data de transação e em caso de falhas, adicionaríamos os erros no próprio active_model (isso facilitaria o uso do do i18n nas views).

O que você acha?

**Comment by hugomaiavieira** [comment]
Acho muito boas ideias!
Realmente, ficará muto melhor com essas modificações na class Order!
Mete bronca ai! =)

**Comment by alexandrebini** [comment]
deixa comigo.
